### ISSUE TITLE
[Bug]: Lock file is already being held

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#1326]
### Describe the issue

![image](https://user-images.githubusercontent.com/101836977/209783542-81adb34e-6dec-4ef0-8e6d-df20605d7169.png)

Lots and lots of lock file already being held, happens quite freqeuently, restarting the container is the only thing that seems to sort it, temporarily

### Steps to reproduce the issue

1.  Just playing using the android app

### Audiobookshelf version

v2.2.11

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you using a USB connected hard drive on Windows file system? As mentioned here #1095

**Comment by barelylit** [comment]
For library, yes. For config, no:

`version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 4517:80
    volumes:
      - z:\Books\:/audiobooks
      - Z:\Family\JoeyBooks:/joey
      - c:\docker\audiobookshelf\config:/config
      - c:\docker\audiobookshelf\metadata:/metadata`

**Comment by advplyr** [comment]
Are you running Docker from Windows

**Comment by barelylit** [comment]
Yeah, Docker Desktop v4.15.0

**Comment by advplyr** [comment]
This issue is specific to windows file systems and I'm not sure what it is. It only impacts a very small percent of users so it is something uncommon with the way the file system is setup I'm guessing.

**Comment by barelylit** [comment]
File system on that drive is NTFS, so ive opened up the permissions to "everyone" to have full control, see if that helps
 (only me on the system so not concerned about security on that folder)

**Comment by Poundsy82** [comment]
I'm seeing the same issue.

Windows server 2022 with NTFS file system. Docker and container installed on an NVME drive while the library is stored on a traditional spinning drive.

There is nothing unusual about my setup, it's just a standalone sata connected drive, no raid arrays or anything else unusable like that.

**Comment by barelylit** [comment]
FWIW, this seems to have resolved the issue, have not seen it re-occuring since opening up the permissions.

Interestingly, I was getting 2 to 3 failures to open a book on first hitting play, it would give error that server playback unavailabile - I had put this down to a moment for a USB drive to spin up perhaps, but this also seems to have been resolved, havent see this since the permissions were opened up

**Comment by Poundsy82** [comment]
@barelylit 

I tried giving full access perms to users on my config and metadata folders but it didn't fix it.
I'll try everyone instead of users on those folders and see if that works.

Like you my system is only me so it's not a big deal.

**Comment by Poundsy82** [comment]
Gave permissions to everyone in both my config and metadata as well as my library folders and also my docker folder as well.

Same problem persisting.

**Comment by barelylit** [comment]
When i changed the permissions on mine, i removed inheritance and replaced permissions on all child objects to ensure there wasnt something burried with the tighter permissions, perhaps worth a try on that? 

I only did it on the c:\docker\audiobookshelf folder, which is effectively just the metadata and config

**Comment by Poundsy82** [comment]
Thanks, will try that. I didn't do that but now have.

**Comment by Poundsy82** [comment]
Yeah hasn't fixed it for me either.

**Comment by Poundsy82** [comment]
I've also tried moving the config folder to the OS drive just to be sure it wasn't some other weird thing going on. No change

**Comment by wtangofoxtrot** [comment]
Same issue here, when i restart i get the below errors at startup followed by the DB errors when trying to play something.
I am running in docker on a ubuntu 22.04
All disks are mounted via a nfs share (no usb involved)
```
[2023-02-18 22:50:01] INFO: [Watcher] "Books" Ready
Error: Stale lock or attempt to update it after release
    at process.<anonymous> (/server/libs/njodb/index.js:101:37)
    at process.emit (node:events:513:28)
    at processEmit [as emit] (/server/libs/signalExit/index.js:204:34)
    at process._fatalException (node:internal/process/execution:149:25) {
  code: 'ECOMPROMISED'
}
Error: Stale lock or attempt to update it after release
    at process.<anonymous> (/server/libs/njodb/index.js:101:37)
    at process.emit (node:events:513:28)
    at processEmit [as emit] (/server/libs/signalExit/index.js:204:34)
    at process._fatalException (node:internal/process/execution:149:25) {
  code: 'ECOMPROMISED'
}
[2023-02-18 22:55:01] INFO: [Server] Socket Connected pSt6CdsHEY6iBdw_AAAB
[2023-02-18 22:55:10] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:391)
[2023-02-18 22:55:37] INFO: [Server] Socket pSt6CdsHEY6iBdw_AAAB disconnected from client "angarg" after 36420ms (Reason: transport close)
[2023-02-18 22:55:38] INFO: [Server] Socket Connected UvQ_1znE2qM7Yj-nAAAD
[2023-02-18 22:55:48] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:391)
[2023-02-18 22:56:10] ERROR: [DB] Update entity user Failed: Error: Lock file is already being held (Db.js:391)
```

**Comment by JamesOEastern** [comment]
So I had a similar issue, with playback not syncing. The solution seems to be "not" running Docker with Admin privileges.

**Comment by plague-doctor** [comment]
This issue has been reported here: https://github.com/advplyr/audiobookshelf/issues/845 and here https://github.com/advplyr/audiobookshelf/issues/653
I workaround this by moving mapping `/config` out of nfs to local drive.
I think those problems will disappear as soon as the database will be moved to sqlite or any other dedicated database. 
@advplyr is this still on your radar? Any progress on that?

**Comment by advplyr** [comment]
Definitely still on my radar. No progress on this yet but there are some discussions going on.

**Comment by cadric** [comment]
I just want to report that I have this error on a Dietpi (debian) server in docker. Just started yesterday :/
Nothing seems to resolve this error and I can no longer add new media.

**Comment by advplyr** [comment]
You have to go into the `/config` folder and delete `.lock` files. Then restart the server.

**Comment by Commiccannon** [comment]
Where in the confic folder are the .lock files found, i have been searching for a while and cannot find them

**Comment by Commiccannon** [comment]
Tried that, still getting errors. If it helps my config directory is stores on my c drive being an ssd with windows, my audiobooks are stored on a RAID5 array in the same pc mounted as D drive

**Comment by advplyr** [comment]
Where is the server running from?

**Comment by Commiccannon** [comment]
Server was running on Windows pc through docker installed via community guidelines. I reinstalled this morning same method however putting the config and metadata folders separately and on the same drive as my audiobooks, will let you know if the issue persists

**Comment by EloquenceWinters** [comment]
Additional data points for you, in case that helps.

I have this issue (resulting in the error popup about progress not being synced), and I'm running:
- Windows 10 Pro
- Docker installed on C: (NVME drive where the OS resides, NTFS)
- data, config, and audiobook files on D: (16TB SATA HDD, NTFS)

Following the suggestion above, I set permissions for the Docker, data, and config folders to Everyone (clearing inheritance and then applying to all files in the folders), but that doesn't seem to fix the problem for me.

Stopping, closing, and restarting Docker fixes it for a time.

**Comment by Commiccannon** [comment]
Only thing that worked permanently has been reinstalling audiobookshelf unfortunately, I recommend making a backup then reinstalling with the backup it only takes half hour or so and has been running fine for me for at least 2 weeks

**Comment by kymahi** [comment]
To add some more context to this, I'm running Docker on an M1 Mac Mini, USB ExFat drive and getting this error for one client.

**Comment by barelylit** [comment]
FWIW, i followed [Commiccannon](https://github.com/Commiccannon) advice and did the following:

1) Backup confirg
2) Took a copy of existing config folders, then deleted
3) Deleted the docker
4) Re-ran the docker and let it build configs
5) Login
6) Restored the backup
7) Restarted the docker

Took less than 5 minutes, and seems to be working fine ever since

**Comment by barelylit** [comment]
Spoke to soon, still fubar.

**Comment by barelylit** [comment]
So, its a bit of a bodge, but I seem to have sorted this with a workaround

I made a virtual hard drive file, of 1gb. Attached and formatted it as Fat32. Moved the config and metadata to the virtual drive to avoid any NTFS permission issues. 

Seems to be working fine so far

https://learn.microsoft.com/en-us/windows-server/storage/disk-management/manage-virtual-hard-disks

**Comment by advplyr** [comment]
The latest release 2.3.3 is using Sqlite now. The library that was being used where this error was coming from is no longer being used.
